### ISSUE TITLE
Nice paste bro

### ISSUE THREAD

**Issue by nyf-tech** [Coolest-PL/aqua_antiping#1]

**Comment by Coolest-PL** [comment]
It's not a copy bro ;)

**Comment by nyf-tech** [comment]
what this do in lua ?
local z = 0

repeat
    
    
z = z +1 

print(z)
until not (z<5)

**Comment by Coolest-PL** [comment]
it will repeat program until local z will be smaller than 5

**Comment by Coolest-PL** [comment]
it will repeat program until local z will be 5

**Comment by Coolest-PL** [comment]
and from whom I copied this script ?
